name: CI

on:
  push:

permissions:
  contents: read

env:
  GO_VERSION: 1.24
  GOLANGCI_LINT_VERSION: v2.1.6

jobs:
  lint-commit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: lint commit messages
        uses: opensource-nepal/commitlint@02e7ff4f7f1e4b1f8e2955b114bfa9271f1c7c97

  lint-go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: lint go
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: test go
        run: go test -v ./...

  release:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [lint-commit, lint-go, test-go]
    permissions:
      contents: write
      issues: write
    steps:
      - name: checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          fetch-tags: true

      - name: semantic-release
        uses: ahmadnassri/action-semantic-release@88650b63adac704a32125faac3983db32805210c
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
